# Generated by Django 2.0.5 on 2019-04-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='constellation',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nickname_pinyin',
        ),
    ]
