# Generated by Django 2.0.5 on 2019-04-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190425_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthentry',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_entries', to='core.Member', verbose_name='OAuth凭据'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauthentry',
            name='unionid',
            field=models.CharField(default=None, max_length=50, verbose_name='Union ID'),
            preserve_default=False,
        ),
    ]
