# Generated by Django 2.0.5 on 2019-04-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190425_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthentry',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oauth_entries', to='core.Member', verbose_name='OAuth凭据'),
        ),
        migrations.AlterField(
            model_name='oauthentry',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户昵称'),
        ),
    ]
