# Generated by Django 2.0.5 on 2019-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190425_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
