# Generated by Django 2.0.5 on 2019-04-25 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190425_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineJudgeProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, verbose_name='题目编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(help_text='直接截取整个题目页面的HTML内容', verbose_name='题目内容')),
            ],
            options={
                'verbose_name': 'OJ问题',
                'verbose_name_plural': 'OJ问题',
                'db_table': 'online_judge_problem',
            },
        ),
        migrations.CreateModel(
            name='OnlineJudgeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('homepage', models.CharField(max_length=255, verbose_name='首页')),
                ('problem_url_template', models.CharField(help_text='题目的网址链接，其中用{num}替代题目编号可以', max_length=255, verbose_name='问题链接')),
                ('problem_title_regex', models.CharField(help_text='正则表达式字符串，提取第一个匹配组作为标题', max_length=255, verbose_name='标题提取正则表达式')),
            ],
            options={
                'verbose_name': 'OJ站点',
                'verbose_name_plural': 'OJ站点',
                'db_table': 'online_judge_site',
            },
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.ProblemCategory', verbose_name='上级')),
            ],
            options={
                'verbose_name': '问题分类',
                'verbose_name_plural': '问题分类',
                'db_table': 'problem_category',
            },
        ),
        migrations.CreateModel(
            name='ProblemPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文内容')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemposts_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('categories', models.ManyToManyField(related_name='posts', to='core.ProblemCategory', verbose_name='标记分类')),
                ('problems', models.ManyToManyField(related_name='posts', to='core.OnlineJudgeProblem', verbose_name='相关题目')),
            ],
            options={
                'verbose_name': '题解',
                'verbose_name_plural': '题解',
                'db_table': 'core_problem_post',
            },
        ),
        migrations.AlterModelOptions(
            name='oauthentry',
            options={'verbose_name': 'OAuth凭据', 'verbose_name_plural': 'OAuth凭据'},
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='core.OnlineJudgeSite', verbose_name='站点'),
        ),
        migrations.AlterUniqueTogether(
            name='onlinejudgeproblem',
            unique_together={('site', 'num')},
        ),
    ]
