# Generated by Django 2.0.5 on 2019-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190425_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesite',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='简写代码'),
            preserve_default=False,
        ),
    ]
