# Generated by Django 2.0.5 on 2019-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_onlinejudgesite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesite',
            name='problem_fail_regex',
            field=models.CharField(blank=True, default='', help_text='有些OJ没有找到题目也会返回200响应，这个时候需要用正则辅助判断是否找不到题目', max_length=255, verbose_name='抓取题目错误正则表达式'),
        ),
    ]
