# Generated by Django 2.0.5 on 2019-04-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_onlinejudgesite_problem_fail_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesite',
            name='problem_content_css_selector',
            field=models.CharField(blank=True, default='', help_text='通过抓取题目的网页 html 内容提取题目正文的 css 选择器', max_length=255, verbose_name='内容提取 css 选择器'),
        ),
    ]
