# Generated by Django 2.0.5 on 2019-04-26 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_onlinejudgesite_problem_content_css_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='problempost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problempost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
