# Generated by Django 2.0.5 on 2019-04-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190428_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problempost',
            old_name='problems',
            new_name='problems_related',
        ),
        migrations.AlterField(
            model_name='problempost',
            name='origin_link',
            field=models.CharField(blank=True, help_text='留空的话视作原创', max_length=250, null=True, unique=True, verbose_name='原文链接'),
        ),
    ]
