# Generated by Django 2.0.5 on 2019-04-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190428_2325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlinejudgeproblem',
            table='core_online_judge_problem',
        ),
        migrations.AlterModelTable(
            name='onlinejudgesite',
            table='core_online_judge_site',
        ),
    ]
