# Generated by Django 2.0.5 on 2019-04-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190429_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempost',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.OnlineJudgeProblem', verbose_name='对应题目'),
            preserve_default=False,
        ),
    ]
