# Generated by Django 2.0.5 on 2019-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190429_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesite',
            name='charset',
            field=models.CharField(default='utf8', max_length=20, verbose_name='网站编码'),
        ),
    ]
