# Generated by Django 2.0.5 on 2019-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempost',
            name='problems_related',
            field=models.ManyToManyField(blank=True, related_name='posts_related', to='core.OnlineJudgeProblem', verbose_name='关联题目'),
        ),
    ]
