# Generated by Django 2.0.5 on 2019-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190429_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcategory',
            name='seq',
            field=models.CharField(blank=True, default=True, max_length=20, verbose_name='序号'),
        ),
    ]
