# Generated by Django 2.2.1 on 2019-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_problemcategory_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='contest_num',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='题目编号'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='题目描述部分，格式为Markdown', verbose_name='题目描述'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='extra_description',
            field=models.TextField(blank=True, default='', help_text='题目描述部分，格式为Markdown', verbose_name='额外题目描述'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='input_samples',
            field=models.TextField(blank=True, default='', help_text='题目输出描述', verbose_name='样例输入'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='input_specification',
            field=models.TextField(blank=True, default='', help_text='题目输入描述', verbose_name='输入描述'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='is_special_judge',
            field=models.BooleanField(default=False, verbose_name='是否SpecialJudge'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='是否同步'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='memory_limit',
            field=models.IntegerField(default=0, help_text='内存限制，单位为KB', verbose_name='内存限制'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='output_samples',
            field=models.TextField(blank=True, default='', help_text='题目输出描述', verbose_name='样例输出'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='output_specification',
            field=models.TextField(blank=True, default='', help_text='题目输出描述', verbose_name='输出描述'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='题目来源'),
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='时间限制，单位为毫秒', verbose_name='时间限制'),
        ),
    ]
