# Generated by Django 2.2.1 on 2019-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190525_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinejudgeproblem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='onlinejudgeproblem',
            name='source',
        ),
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='extra_info',
            field=models.TextField(blank=True, help_text='一些不好定位的附加信息，用 JSON 传入', verbose_name='额外信息'),
        ),
    ]
