# Generated by Django 2.2.1 on 2019-05-28 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_auto_20190525_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.Comment', verbose_name='上级'),
        ),
        migrations.AlterField(
            model_name='onlinejudgeproblem',
            name='content',
            field=models.TextField(blank=True, help_text='直接截取整个题目页面的HTML内容', verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='onlinejudgeproblem',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.ProblemCategory', verbose_name='上级'),
        ),
        migrations.CreateModel(
            name='OnlineJudgeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('GCC', 'GCC'), ('GPP', 'G++'), ('CPP11', 'C++11'), ('FPC', 'FPC'), ('JAVA', 'Java'), ('PYTHON2', 'Python2'), ('PYTHON3', 'Python3'), ('PERL', 'Perl'), ('SCHEME', 'Scheme'), ('PHP', 'PHP')], max_length=30, verbose_name='语言')),
                ('code', models.TextField(blank=True, default='', verbose_name='代码')),
                ('result', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEED', 'Time Limit Exceed'), ('MEMORY_LIMIT_EXCEED', 'Memory Limit Exceed'), ('RUNTIME_ERROR', 'Runtime Error'), ('SEGMENT_FAULT', 'Segment Fault'), ('COMPILATION_ERROR', 'Compilation Error'), ('NON_ZERO_EXIT_CODE', 'Non Zero Exit Code'), ('OUTPUT_LIMIT_EXCEED', 'Output Limit Exceed'), ('PRESENTATION_ERROR', 'Presentation Error'), ('FLOAT_POINT_ERROR', 'Float Point Error')], default='', max_length=30, verbose_name='结果')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onlinejudgesubmissions_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.OnlineJudgeProblem', verbose_name='题目')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'core_online_judge_submission',
            },
        ),
        migrations.CreateModel(
            name='OnlineJudgeUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='密码')),
                ('session_info', models.TextField(blank=True, default='', verbose_name='会话信息')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.OnlineJudgeSite', verbose_name='OJ站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_judge_profiles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'OJ用户档案',
                'verbose_name_plural': 'OJ用户档案',
                'db_table': 'core_online_judge_user_profile',
                'unique_together': {('site', 'user')},
            },
        ),
    ]
