# Generated by Django 2.2.1 on 2019-05-28 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190528_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgeuserprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinejudgeuserprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间'),
        ),
    ]
