# Generated by Django 2.2.1 on 2019-05-28 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190528_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesubmission',
            name='submission_id',
            field=models.IntegerField(default=0, verbose_name='OJ提交编号'),
        ),
        migrations.AddField(
            model_name='onlinejudgesubmission',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
    ]
