# Generated by Django 2.2.1 on 2019-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190528_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgesubmission',
            name='run_memory',
            field=models.IntegerField(default=0, verbose_name='运行内存'),
        ),
        migrations.AddField(
            model_name='onlinejudgesubmission',
            name='run_time',
            field=models.IntegerField(default=0, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='onlinejudgesubmission',
            name='language',
            field=models.CharField(choices=[('', ''), ('C', 'C'), ('GCC', 'GCC'), ('GPP', 'G++'), ('CPP11', 'C++11'), ('FPC', 'FPC'), ('JAVA', 'Java'), ('PYTHON2', 'Python2'), ('PYTHON3', 'Python3'), ('PERL', 'Perl'), ('SCHEME', 'Scheme'), ('PHP', 'PHP')], max_length=30, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='onlinejudgesubmission',
            name='result',
            field=models.CharField(blank=True, choices=[('', ''), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEED', 'Time Limit Exceed'), ('MEMORY_LIMIT_EXCEED', 'Memory Limit Exceed'), ('RUNTIME_ERROR', 'Runtime Error'), ('SEGMENT_FAULT', 'Segment Fault'), ('COMPILATION_ERROR', 'Compilation Error'), ('NON_ZERO_EXIT_CODE', 'Non Zero Exit Code'), ('OUTPUT_LIMIT_EXCEED', 'Output Limit Exceed'), ('PRESENTATION_ERROR', 'Presentation Error'), ('FLOAT_POINT_ERROR', 'Float Point Error')], default='', max_length=30, verbose_name='结果'),
        ),
    ]
