# Generated by Django 2.2.1 on 2019-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190528_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinejudgeproblem',
            name='supported_languages',
            field=models.CharField(blank=True, default='', help_text='指定该题目支持提交的语言，用 | 分割，如果没有填写，则为继承 OJ 的语言列表', max_length=255, verbose_name='支持语言'),
        ),
        migrations.AddField(
            model_name='onlinejudgesite',
            name='supported_languages',
            field=models.CharField(blank=True, default='', help_text='指定该题目支持提交的语言，用 | 分割', max_length=255, verbose_name='支持语言'),
        ),
    ]
