# Generated by Django 2.2.1 on 2019-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190529_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinejudgesite',
            name='supported_languages',
        ),
        migrations.AddField(
            model_name='onlinejudgesubmission',
            name='language_id',
            field=models.CharField(blank=True, help_text='OJ的内部语言编号', max_length=30, verbose_name='语言ID'),
        ),
        migrations.AlterField(
            model_name='onlinejudgesubmission',
            name='language',
            field=models.CharField(choices=[('', ''), ('C', 'C'), ('FPC', 'FPC'), ('JAVA', 'Java'), ('PYTHON2', 'Python2'), ('PYTHON3', 'Python3'), ('PERL', 'Perl'), ('SCHEME', 'Scheme'), ('PHP', 'PHP')], max_length=30, verbose_name='语言'),
        ),
    ]
