# Generated by Django 2.2.1 on 2019-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190802_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinejudgesubmission',
            name='language',
            field=models.CharField(choices=[('', ''), ('RAW', 'Raw'), ('C', 'C'), ('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON2', 'Python2'), ('PYTHON3', 'Python3'), ('PASCAL', 'Pascal'), ('DELPHI', 'Delphi'), ('RUBY', 'Ruby'), ('CSHARP', 'C#'), ('VB', 'Visual Basic'), ('HASKELL', 'Haskell'), ('OCAML', 'OCaml'), ('SCALA', 'Scala'), ('D', 'D'), ('GO', 'Go'), ('JAVASCRIPT', 'JavaScript'), ('KOTLIN', 'Kotlin'), ('RUST', 'Rust'), ('CLANG', 'Clang'), ('NODEJS', 'Node.js'), ('PERL', 'Perl'), ('SCHEME', 'Scheme'), ('PHP', 'PHP'), ('BASH', 'Bash')], max_length=30, verbose_name='语言'),
        ),
    ]
